print("Twinkle, twinkle,little star,")
print("\tHow i wonder what you are!")
print("\t\tUp above the world so high,")
print("\t\tLike a diamond in the sky.")
print("Twinkle,twinkle,litttle star,")
print("\tHow i wonder what you are.")
